### ISSUE TITLE
click on compass

### ISSUE THREAD

**Issue by Milad0071** [cXiaof/maptalks.control.compass#7]
hello my friend. i wish you are fine. i need to write a function for when user clicks on the compass. i am using raw javascript. is there any solution for this?

**Comment by cXiaof** [comment]
Thanks for the issue. I'll try to support some events on this weekend.

**Comment by Milad0071** [comment]
> Thanks for the issue. I'll try to support some events on this weekend.

thank you very much

**Comment by cXiaof** [comment]
resolved in latest release.

**Comment by Milad0071** [comment]
thank you
